name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: 'actions'
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          configuration: phpunit.xml
          php_extensions: xdebug
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
